spring:
  aop:
    auto: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 项目编码（必须）
  project:
    name: itservice-010
  # 应用编码（必须）
  application:
    name: it-service-front-manage
  # 环境 （必须）可选择值 DEV|FAT|UAT|PRO （对应logback-spring.xml中的日志输出）
  profiles:
    active: pro

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.yonghui.it.service.front.manage.domain.entity
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      column-underline: true
      refresh-mapper: true
      # 数据库大写下划线转换
      #capital-mode: true
      # 逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    # 注意：单引号
    jdbc-type-for-null: 'null'

# SQL性能分析,有性能损耗,生产环境禁止开启！！！
performanceInterceptor:
  # 是否启用
  enable: ${PERFORMANCE_INTERCEPTOR:false}
  # SQL 最大执行时长ms
  maxTime: 2000

feign:
  hystrix:
    enabled: true